### ISSUE TITLE
Is it possible to have strong name assembly

### ISSUE THREAD

**Issue by vhatsura** [Deffiss/testenvironment-docker#15]
Hey, @Deffiss.

Thanks a lot for such a great library. I was in DotNext in 2018 in Moscow and saw your presentation. It was awesome.

So, I'm using `TestEnvironment.Docker` package in a few projects and faced with an issue in one of the projects. Such a project has strong naming and has two targets: net461 and netcoreapp2.2. Unfortunately, `TestEnvironment.Docker` package  cannot be used in net461 due to it isn't strong-named assembly:

```
System.IO.FileLoadException
Could not load file or assembly 'TestEnvironment.Docker, Version=1.2.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

Also, the fresh guide from Microsoft about open-source libraries [suggests signing libraries](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming).
It would be very nice if you can do it.

**Comment by jzabroski** [comment]
@vhatsura  Use the StrongNamer package instead, maintained by Daniel Plaisted of the Microsoft SDK team.  There is no need for TestEnvironment.Docker to start strong naming things.

**Comment by vhatsura** [comment]
@jzabroski, didn't know about another great library. Thanks a lot. Will add it to my bookmarks.

**Comment by jzabroski** [comment]
Basically, the open source guidance is a bit misguided and not in-sync with reality.  In an ideal world, open source projects would Authenticode their Nuget Packages, but nobody does that because it costs money to have a server up to store secrets to sign nuget packages.  So, what one person at Microsoft might write as a best practice is a far cry from what we normally think of as a "best practice" in the ".NET Framework Design Guidelines" sense of "end base classes with Base" that are easy to follow.

Anyway, StrongNamer works - I used it to sign a bunch of Excel COM Add-ins recently on a massive project where I had to sign about 50 projects.
